### ISSUE TITLE
How to convert hifigan V3 to haiku correctly?

### ISSUE THREAD

**Issue by nampdn** [NTT123/vietTTS#24]
Hi,
I'm trying to using `resblock: 2` on HiFi-Gan config `v3`. Could you please help me to fix the convert script so that it could inference correctly?

Using the model converted from the [convert_torch_model_to_haiku.py](https://github.com/NTT123/vietTTS/blob/master/vietTTS/hifigan/convert_torch_model_to_haiku.py) not work with v3.

Here is the error I'm dealing with:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/vietTTS/vietTTS/synthesizer.py", line 38, in <module>
    wave = mel2wave(mel)
  File "/content/vietTTS/vietTTS/hifigan/mel2wave.py", line 40, in mel2wave
    wav, aux = forward.apply(params, aux, rng, mel)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/transform.py", line 400, in apply_fn
    out = f(*args, **kwargs)
  File "/content/vietTTS/vietTTS/hifigan/mel2wave.py", line 32, in forward
    return net(x)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 433, in wrapped
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 284, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/content/vietTTS/vietTTS/hifigan/model.py", line 119, in __call__
    xs = self.resblocks[i * self.num_kernels + j](x)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 433, in wrapped
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 284, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/content/vietTTS/vietTTS/hifigan/model.py", line 72, in __call__
    xt = c(xt)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 433, in wrapped
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/module.py", line 284, in run_interceptors
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/conv.py", line 200, in __call__
    w = hk.get_parameter("w", w_shape, inputs.dtype, init=w_init)
  File "/usr/local/lib/python3.7/dist-packages/haiku/_src/base.py", line 333, in get_parameter
    name, bundle_name))
ValueError: Unable to retrieve parameter 'w' for module 'generator/~/res_block1_0/~/conv1_d'. All parameters must be created as part of `init`.
```

**Comment by NTT123** [comment]
Hi! You may need to modify this line 
https://github.com/NTT123/vietTTS/blob/8d2ee1f1d6542efd7647866bf4c1803b5eefe487/vietTTS/hifigan/convert_torch_model_to_haiku.py#L45
with
```
a = f"generator/~/res_block2_{x}/~/{y}_{z}" 
```

**Comment by nampdn** [comment]
> Hi! You may need to modify this line
> 
> https://github.com/NTT123/vietTTS/blob/8d2ee1f1d6542efd7647866bf4c1803b5eefe487/vietTTS/hifigan/convert_torch_model_to_haiku.py#L45
> 
> 
> with
> ```
> a = f"generator/~/res_block2_{x}/~/{y}_{z}" 
> ```

Thank you so much,
I've read the code and guess I have to modify that line, but after modifying as you've said and I re-convert it. I'm also meet this error:



```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 82, in <module>
    main()
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 78, in main
    convert_to_haiku(a, h, device)
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 30, in convert_to_haiku
    generator.load_state_dict(state_dict_g["generator"])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "ups.3.bias", "ups.3.weight_g", "ups.3.weight_v", "resblocks.0.convs1.0.bias", "resblocks.0.convs1.0.weight_g", "resblocks.0.convs1.0.weight_v", "resblocks.0.convs1.1.bias", "resblocks.0.convs1.1.weight_g", "resblocks.0.convs1.1.weight_v", "resblocks.0.convs1.2.bias", "resblocks.0.convs1.2.weight_g", "resblocks.0.convs1.2.weight_v", "resblocks.0.convs2.0.bias", "resblocks.0.convs2.0.weight_g", "resblocks.0.convs2.0.weight_v", "resblocks.0.convs2.1.bias", "resblocks.0.convs2.1.weight_g", "resblocks.0.convs2.1.weight_v", "resblocks.0.convs2.2.bias", "resblocks.0.convs2.2.weight_g", "resblocks.0.convs2.2.weight_v", "resblocks.1.convs1.0.bias", "resblocks.1.convs1.0.weight_g", "resblocks.1.convs1.0.weight_v", "resblocks.1.convs1.1.bias", "resblocks.1.convs1.1.weight_g", "resblocks.1.convs1.1.weight_v", "resblocks.1.convs1.2.bias", "resblocks.1.convs1.2.weight_g", "resblocks.1.convs1.2.weight_v", "resblocks.1.convs2.0.bias", "resblocks.1.convs2.0.weight_g", "resblocks.1.convs2.0.weight_v", "resblocks.1.convs2.1.bias", "resblocks.1.convs2.1.weight_g", "resblocks.1.convs2.1.weight_v", "resblocks.1.convs2.2.bias", "resblocks.1.convs2.2.weight_g", "resblocks.1.convs2.2.weight_v", "resblocks.2.convs1.0.bias", "resblocks.2.convs1.0.weight_g", "resblocks.2.convs1.0.weight_v", "resblocks.2.convs1.1.bias", "resblocks.2.convs1.1.weight_g", "resblocks.2.convs1.1.weight_v", "resblocks.2.convs1.2.bias", "resblocks.2.convs1.2.weight_g", "resblocks.2.convs1.2.weight_v", "resblocks.2.convs2.0.bias", "resblocks.2.convs2.0.weight_g", "resblocks.2.convs2.0.weight_v", "resblocks.2.convs2.1.bias", "resblocks.2.convs2.1.weight_g", "resblocks.2.convs2.1.weight_v", "resblocks.2.convs2.2.bias", "resblocks.2.convs2.2.weight_g", "resblocks.2.convs2.2.weight_v", "resblocks.3.convs1.0.bias", "resblocks.3.convs1.0.weight_g", "resblocks.3.convs1.0.weight_v", "resblocks.3.convs1.1.bias", "resblocks.3.convs1.1.weight_g", "resblocks.3.convs1.1.weight_v", "resblocks.3.convs1.2.bias", "resblocks.3.convs1.2.weight_g", "resblocks.3.convs1.2.weight_v", "resblocks.3.convs2.0.bias", "resblocks.3.convs2.0.weight_g", "resblocks.3.convs2.0.weight_v", "resblocks.3.convs2.1.bias", "resblocks.3.convs2.1.weight_g", "resblocks.3.convs2.1.weight_v", "resblocks.3.convs2.2.bias", "resblocks.3.convs2.2.weight_g", "resblocks.3.convs2.2.weight_v", "resblocks.4.convs1.0.bias", "resblocks.4.convs1.0.weight_g", "resblocks.4.convs1.0.weight_v", "resblocks.4.convs1.1.bias", "resblocks.4.convs1.1.weight_g", "resblocks.4.convs1.1.weight_v", "resblocks.4.convs1.2.bias", "resblocks.4.convs1.2.weight_g", "resblocks.4.convs1.2.weight_v", "resblocks.4.convs2.0.bias", "resblocks.4.convs2.0.weight_g", "resblocks.4.convs2.0.weight_v", "resblocks.4.convs2.1.bias", "resblocks.4.convs2.1.weight_g", "resblocks.4.convs2.1.weight_v", "resblocks.4.convs2.2.bias", "resblocks.4.convs2.2.weight_g", "resblocks.4.convs2.2.weight_v", "resblocks.5.convs1.0.bias", "resblocks.5.convs1.0.weight_g", "resblocks.5.convs1.0.weight_v", "resblocks.5.convs1.1.bias", "resblocks.5.convs1.1.weight_g", "resblocks.5.convs1.1.weight_v", "resblocks.5.convs1.2.bias", "resblocks.5.convs1.2.weight_g", "resblocks.5.convs1.2.weight_v", "resblocks.5.convs2.0.bias", "resblocks.5.convs2.0.weight_g", "resblocks.5.convs2.0.weight_v", "resblocks.5.convs2.1.bias", "resblocks.5.convs2.1.weight_g", "resblocks.5.convs2.1.weight_v", "resblocks.5.convs2.2.bias", "resblocks.5.convs2.2.weight_g", "resblocks.5.convs2.2.weight_v", "resblocks.6.convs1.0.bias", "resblocks.6.convs1.0.weight_g", "resblocks.6.convs1.0.weight_v", "resblocks.6.convs1.1.bias", "resblocks.6.convs1.1.weight_g", "resblocks.6.convs1.1.weight_v", "resblocks.6.convs1.2.bias", "resblocks.6.convs1.2.weight_g", "resblocks.6.convs1.2.weight_v", "resblocks.6.convs2.0.bias", "resblocks.6.convs2.0.weight_g", "resblocks.6.convs2.0.weight_v", "resblocks.6.convs2.1.bias", "resblocks.6.convs2.1.weight_g", "resblocks.6.convs2.1.weight_v", "resblocks.6.convs2.2.bias", "resblocks.6.convs2.2.weight_g", "resblocks.6.convs2.2.weight_v", "resblocks.7.convs1.0.bias", "resblocks.7.convs1.0.weight_g", "resblocks.7.convs1.0.weight_v", "resblocks.7.convs1.1.bias", "resblocks.7.convs1.1.weight_g", "resblocks.7.convs1.1.weight_v", "resblocks.7.convs1.2.bias", "resblocks.7.convs1.2.weight_g", "resblocks.7.convs1.2.weight_v", "resblocks.7.convs2.0.bias", "resblocks.7.convs2.0.weight_g", "resblocks.7.convs2.0.weight_v", "resblocks.7.convs2.1.bias", "resblocks.7.convs2.1.weight_g", "resblocks.7.convs2.1.weight_v", "resblocks.7.convs2.2.bias", "resblocks.7.convs2.2.weight_g", "resblocks.7.convs2.2.weight_v", "resblocks.8.convs1.0.bias", "resblocks.8.convs1.0.weight_g", "resblocks.8.convs1.0.weight_v", "resblocks.8.convs1.1.bias", "resblocks.8.convs1.1.weight_g", "resblocks.8.convs1.1.weight_v", "resblocks.8.convs1.2.bias", "resblocks.8.convs1.2.weight_g", "resblocks.8.convs1.2.weight_v", "resblocks.8.convs2.0.bias", "resblocks.8.convs2.0.weight_g", "resblocks.8.convs2.0.weight_v", "resblocks.8.convs2.1.bias", "resblocks.8.convs2.1.weight_g", "resblocks.8.convs2.1.weight_v", "resblocks.8.convs2.2.bias", "resblocks.8.convs2.2.weight_g", "resblocks.8.convs2.2.weight_v", "resblocks.9.convs1.0.bias", "resblocks.9.convs1.0.weight_g", "resblocks.9.convs1.0.weight_v", "resblocks.9.convs1.1.bias", "resblocks.9.convs1.1.weight_g", "resblocks.9.convs1.1.weight_v", "resblocks.9.convs1.2.bias", "resblocks.9.convs1.2.weight_g", "resblocks.9.convs1.2.weight_v", "resblocks.9.convs2.0.bias", "resblocks.9.convs2.0.weight_g", "resblocks.9.convs2.0.weight_v", "resblocks.9.convs2.1.bias", "resblocks.9.convs2.1.weight_g", "resblocks.9.convs2.1.weight_v", "resblocks.9.convs2.2.bias", "resblocks.9.convs2.2.weight_g", "resblocks.9.convs2.2.weight_v", "resblocks.10.convs1.0.bias", "resblocks.10.convs1.0.weight_g", "resblocks.10.convs1.0.weight_v", "resblocks.10.convs1.1.bias", "resblocks.10.convs1.1.weight_g", "resblocks.10.convs1.1.weight_v", "resblocks.10.convs1.2.bias", "resblocks.10.convs1.2.weight_g", "resblocks.10.convs1.2.weight_v", "resblocks.10.convs2.0.bias", "resblocks.10.convs2.0.weight_g", "resblocks.10.convs2.0.weight_v", "resblocks.10.convs2.1.bias", "resblocks.10.convs2.1.weight_g", "resblocks.10.convs2.1.weight_v", "resblocks.10.convs2.2.bias", "resblocks.10.convs2.2.weight_g", "resblocks.10.convs2.2.weight_v", "resblocks.11.convs1.0.bias", "resblocks.11.convs1.0.weight_g", "resblocks.11.convs1.0.weight_v", "resblocks.11.convs1.1.bias", "resblocks.11.convs1.1.weight_g", "resblocks.11.convs1.1.weight_v", "resblocks.11.convs1.2.bias", "resblocks.11.convs1.2.weight_g", "resblocks.11.convs1.2.weight_v", "resblocks.11.convs2.0.bias", "resblocks.11.convs2.0.weight_g", "resblocks.11.convs2.0.weight_v", "resblocks.11.convs2.1.bias", "resblocks.11.convs2.1.weight_g", "resblocks.11.convs2.1.weight_v", "resblocks.11.convs2.2.bias", "resblocks.11.convs2.2.weight_g", "resblocks.11.convs2.2.weight_v". 
	Unexpected key(s) in state_dict: "resblocks.0.convs.0.bias", "resblocks.0.convs.0.weight_g", "resblocks.0.convs.0.weight_v", "resblocks.0.convs.1.bias", "resblocks.0.convs.1.weight_g", "resblocks.0.convs.1.weight_v", "resblocks.1.convs.0.bias", "resblocks.1.convs.0.weight_g", "resblocks.1.convs.0.weight_v", "resblocks.1.convs.1.bias", "resblocks.1.convs.1.weight_g", "resblocks.1.convs.1.weight_v", "resblocks.2.convs.0.bias", "resblocks.2.convs.0.weight_g", "resblocks.2.convs.0.weight_v", "resblocks.2.convs.1.bias", "resblocks.2.convs.1.weight_g", "resblocks.2.convs.1.weight_v", "resblocks.3.convs.0.bias", "resblocks.3.convs.0.weight_g", "resblocks.3.convs.0.weight_v", "resblocks.3.convs.1.bias", "resblocks.3.convs.1.weight_g", "resblocks.3.convs.1.weight_v", "resblocks.4.convs.0.bias", "resblocks.4.convs.0.weight_g", "resblocks.4.convs.0.weight_v", "resblocks.4.convs.1.bias", "resblocks.4.convs.1.weight_g", "resblocks.4.convs.1.weight_v", "resblocks.5.convs.0.bias", "resblocks.5.convs.0.weight_g", "resblocks.5.convs.0.weight_v", "resblocks.5.convs.1.bias", "resblocks.5.convs.1.weight_g", "resblocks.5.convs.1.weight_v", "resblocks.6.convs.0.bias", "resblocks.6.convs.0.weight_g", "resblocks.6.convs.0.weight_v", "resblocks.6.convs.1.bias", "resblocks.6.convs.1.weight_g", "resblocks.6.convs.1.weight_v", "resblocks.7.convs.0.bias", "resblocks.7.convs.0.weight_g", "resblocks.7.convs.0.weight_v", "resblocks.7.convs.1.bias", "resblocks.7.convs.1.weight_g", "resblocks.7.convs.1.weight_v", "resblocks.8.convs.0.bias", "resblocks.8.convs.0.weight_g", "resblocks.8.convs.0.weight_v", "resblocks.8.convs.1.bias", "resblocks.8.convs.1.weight_g", "resblocks.8.convs.1.weight_v". 
	size mismatch for conv_pre.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for conv_pre.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for conv_pre.weight_v: copying a param with shape torch.Size([256, 80, 7]) from checkpoint, the shape in current model is torch.Size([512, 80, 7]).
	size mismatch for ups.0.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for ups.0.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1, 1]).
	size mismatch for ups.0.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([512, 256, 16]).
	size mismatch for ups.1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for ups.1.weight_g: copying a param with shape torch.Size([128, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
	size mismatch for ups.1.weight_v: copying a param with shape torch.Size([128, 64, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 16]).
	size mismatch for ups.2.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ups.2.weight_g: copying a param with shape torch.Size([64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 1, 1]).
	size mismatch for ups.2.weight_v: copying a param with shape torch.Size([64, 32, 8]) from checkpoint, the shape in current model is torch.Size([128, 64, 4]).
```

**Comment by nampdn** [comment]
Hi @NTT123,
I've tried to replace the config to v3 in `assets/hifigan/config.json` with the file same as [config_v3.json](https://github.com/jik876/hifi-gan/blob/master/config_v3.json)
Then update the code same as this [commit](https://github.com/NTT123/vietTTS/commit/8b4438e9f17462aeadf50c27c193d7ed1b1bfb3e#diff-e8aabb0105b8f5048f7c0704ef9a9454e31f80fcc44c1763cffc7c97ebe6dbbeR45) but my v3 has some error about the keys:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 83, in <module>
    main()
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 79, in main
    convert_to_haiku(a, h, device)
  File "/content/vietTTS/vietTTS/hifigan/convert_torch_model_to_haiku.py", line 30, in convert_to_haiku
    generator.load_state_dict(state_dict_g["generator"])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1498, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "resblocks.0.convs.0.bias", "resblocks.0.convs.0.weight_g", "resblocks.0.convs.0.weight_v", "resblocks.0.convs.1.bias", "resblocks.0.convs.1.weight_g", "resblocks.0.convs.1.weight_v", "resblocks.1.convs.0.bias", "resblocks.1.convs.0.weight_g", "resblocks.1.convs.0.weight_v", "resblocks.1.convs.1.bias", "resblocks.1.convs.1.weight_g", "resblocks.1.convs.1.weight_v", "resblocks.2.convs.0.bias", "resblocks.2.convs.0.weight_g", "resblocks.2.convs.0.weight_v", "resblocks.2.convs.1.bias", "resblocks.2.convs.1.weight_g", "resblocks.2.convs.1.weight_v", "resblocks.3.convs.0.bias", "resblocks.3.convs.0.weight_g", "resblocks.3.convs.0.weight_v", "resblocks.3.convs.1.bias", "resblocks.3.convs.1.weight_g", "resblocks.3.convs.1.weight_v", "resblocks.4.convs.0.bias", "resblocks.4.convs.0.weight_g", "resblocks.4.convs.0.weight_v", "resblocks.4.convs.1.bias", "resblocks.4.convs.1.weight_g", "resblocks.4.convs.1.weight_v", "resblocks.5.convs.0.bias", "resblocks.5.convs.0.weight_g", "resblocks.5.convs.0.weight_v", "resblocks.5.convs.1.bias", "resblocks.5.convs.1.weight_g", "resblocks.5.convs.1.weight_v", "resblocks.6.convs.0.bias", "resblocks.6.convs.0.weight_g", "resblocks.6.convs.0.weight_v", "resblocks.6.convs.1.bias", "resblocks.6.convs.1.weight_g", "resblocks.6.convs.1.weight_v", "resblocks.7.convs.0.bias", "resblocks.7.convs.0.weight_g", "resblocks.7.convs.0.weight_v", "resblocks.7.convs.1.bias", "resblocks.7.convs.1.weight_g", "resblocks.7.convs.1.weight_v", "resblocks.8.convs.0.bias", "resblocks.8.convs.0.weight_g", "resblocks.8.convs.0.weight_v", "resblocks.8.convs.1.bias", "resblocks.8.convs.1.weight_g", "resblocks.8.convs.1.weight_v". 
	Unexpected key(s) in state_dict: "ups.3.bias", "ups.3.weight_g", "ups.3.weight_v", "resblocks.9.convs1.0.bias", "resblocks.9.convs1.0.weight_g", "resblocks.9.convs1.0.weight_v", "resblocks.9.convs1.1.bias", "resblocks.9.convs1.1.weight_g", "resblocks.9.convs1.1.weight_v", "resblocks.9.convs1.2.bias", "resblocks.9.convs1.2.weight_g", "resblocks.9.convs1.2.weight_v", "resblocks.9.convs2.0.bias", "resblocks.9.convs2.0.weight_g", "resblocks.9.convs2.0.weight_v", "resblocks.9.convs2.1.bias", "resblocks.9.convs2.1.weight_g", "resblocks.9.convs2.1.weight_v", "resblocks.9.convs2.2.bias", "resblocks.9.convs2.2.weight_g", "resblocks.9.convs2.2.weight_v", "resblocks.10.convs1.0.bias", "resblocks.10.convs1.0.weight_g", "resblocks.10.convs1.0.weight_v", "resblocks.10.convs1.1.bias", "resblocks.10.convs1.1.weight_g", "resblocks.10.convs1.1.weight_v", "resblocks.10.convs1.2.bias", "resblocks.10.convs1.2.weight_g", "resblocks.10.convs1.2.weight_v", "resblocks.10.convs2.0.bias", "resblocks.10.convs2.0.weight_g", "resblocks.10.convs2.0.weight_v", "resblocks.10.convs2.1.bias", "resblocks.10.convs2.1.weight_g", "resblocks.10.convs2.1.weight_v", "resblocks.10.convs2.2.bias", "resblocks.10.convs2.2.weight_g", "resblocks.10.convs2.2.weight_v", "resblocks.11.convs1.0.bias", "resblocks.11.convs1.0.weight_g", "resblocks.11.convs1.0.weight_v", "resblocks.11.convs1.1.bias", "resblocks.11.convs1.1.weight_g", "resblocks.11.convs1.1.weight_v", "resblocks.11.convs1.2.bias", "resblocks.11.convs1.2.weight_g", "resblocks.11.convs1.2.weight_v", "resblocks.11.convs2.0.bias", "resblocks.11.convs2.0.weight_g", "resblocks.11.convs2.0.weight_v", "resblocks.11.convs2.1.bias", "resblocks.11.convs2.1.weight_g", "resblocks.11.convs2.1.weight_v", "resblocks.11.convs2.2.bias", "resblocks.11.convs2.2.weight_g", "resblocks.11.convs2.2.weight_v", "resblocks.0.convs1.0.bias", "resblocks.0.convs1.0.weight_g", "resblocks.0.convs1.0.weight_v", "resblocks.0.convs1.1.bias", "resblocks.0.convs1.1.weight_g", "resblocks.0.convs1.1.weight_v", "resblocks.0.convs1.2.bias", "resblocks.0.convs1.2.weight_g", "resblocks.0.convs1.2.weight_v", "resblocks.0.convs2.0.bias", "resblocks.0.convs2.0.weight_g", "resblocks.0.convs2.0.weight_v", "resblocks.0.convs2.1.bias", "resblocks.0.convs2.1.weight_g", "resblocks.0.convs2.1.weight_v", "resblocks.0.convs2.2.bias", "resblocks.0.convs2.2.weight_g", "resblocks.0.convs2.2.weight_v", "resblocks.1.convs1.0.bias", "resblocks.1.convs1.0.weight_g", "resblocks.1.convs1.0.weight_v", "resblocks.1.convs1.1.bias", "resblocks.1.convs1.1.weight_g", "resblocks.1.convs1.1.weight_v", "resblocks.1.convs1.2.bias", "resblocks.1.convs1.2.weight_g", "resblocks.1.convs1.2.weight_v", "resblocks.1.convs2.0.bias", "resblocks.1.convs2.0.weight_g", "resblocks.1.convs2.0.weight_v", "resblocks.1.convs2.1.bias", "resblocks.1.convs2.1.weight_g", "resblocks.1.convs2.1.weight_v", "resblocks.1.convs2.2.bias", "resblocks.1.convs2.2.weight_g", "resblocks.1.convs2.2.weight_v", "resblocks.2.convs1.0.bias", "resblocks.2.convs1.0.weight_g", "resblocks.2.convs1.0.weight_v", "resblocks.2.convs1.1.bias", "resblocks.2.convs1.1.weight_g", "resblocks.2.convs1.1.weight_v", "resblocks.2.convs1.2.bias", "resblocks.2.convs1.2.weight_g", "resblocks.2.convs1.2.weight_v", "resblocks.2.convs2.0.bias", "resblocks.2.convs2.0.weight_g", "resblocks.2.convs2.0.weight_v", "resblocks.2.convs2.1.bias", "resblocks.2.convs2.1.weight_g", "resblocks.2.convs2.1.weight_v", "resblocks.2.convs2.2.bias", "resblocks.2.convs2.2.weight_g", "resblocks.2.convs2.2.weight_v", "resblocks.3.convs1.0.bias", "resblocks.3.convs1.0.weight_g", "resblocks.3.convs1.0.weight_v", "resblocks.3.convs1.1.bias", "resblocks.3.convs1.1.weight_g", "resblocks.3.convs1.1.weight_v", "resblocks.3.convs1.2.bias", "resblocks.3.convs1.2.weight_g", "resblocks.3.convs1.2.weight_v", "resblocks.3.convs2.0.bias", "resblocks.3.convs2.0.weight_g", "resblocks.3.convs2.0.weight_v", "resblocks.3.convs2.1.bias", "resblocks.3.convs2.1.weight_g", "resblocks.3.convs2.1.weight_v", "resblocks.3.convs2.2.bias", "resblocks.3.convs2.2.weight_g", "resblocks.3.convs2.2.weight_v", "resblocks.4.convs1.0.bias", "resblocks.4.convs1.0.weight_g", "resblocks.4.convs1.0.weight_v", "resblocks.4.convs1.1.bias", "resblocks.4.convs1.1.weight_g", "resblocks.4.convs1.1.weight_v", "resblocks.4.convs1.2.bias", "resblocks.4.convs1.2.weight_g", "resblocks.4.convs1.2.weight_v", "resblocks.4.convs2.0.bias", "resblocks.4.convs2.0.weight_g", "resblocks.4.convs2.0.weight_v", "resblocks.4.convs2.1.bias", "resblocks.4.convs2.1.weight_g", "resblocks.4.convs2.1.weight_v", "resblocks.4.convs2.2.bias", "resblocks.4.convs2.2.weight_g", "resblocks.4.convs2.2.weight_v", "resblocks.5.convs1.0.bias", "resblocks.5.convs1.0.weight_g", "resblocks.5.convs1.0.weight_v", "resblocks.5.convs1.1.bias", "resblocks.5.convs1.1.weight_g", "resblocks.5.convs1.1.weight_v", "resblocks.5.convs1.2.bias", "resblocks.5.convs1.2.weight_g", "resblocks.5.convs1.2.weight_v", "resblocks.5.convs2.0.bias", "resblocks.5.convs2.0.weight_g", "resblocks.5.convs2.0.weight_v", "resblocks.5.convs2.1.bias", "resblocks.5.convs2.1.weight_g", "resblocks.5.convs2.1.weight_v", "resblocks.5.convs2.2.bias", "resblocks.5.convs2.2.weight_g", "resblocks.5.convs2.2.weight_v", "resblocks.6.convs1.0.bias", "resblocks.6.convs1.0.weight_g", "resblocks.6.convs1.0.weight_v", "resblocks.6.convs1.1.bias", "resblocks.6.convs1.1.weight_g", "resblocks.6.convs1.1.weight_v", "resblocks.6.convs1.2.bias", "resblocks.6.convs1.2.weight_g", "resblocks.6.convs1.2.weight_v", "resblocks.6.convs2.0.bias", "resblocks.6.convs2.0.weight_g", "resblocks.6.convs2.0.weight_v", "resblocks.6.convs2.1.bias", "resblocks.6.convs2.1.weight_g", "resblocks.6.convs2.1.weight_v", "resblocks.6.convs2.2.bias", "resblocks.6.convs2.2.weight_g", "resblocks.6.convs2.2.weight_v", "resblocks.7.convs1.0.bias", "resblocks.7.convs1.0.weight_g", "resblocks.7.convs1.0.weight_v", "resblocks.7.convs1.1.bias", "resblocks.7.convs1.1.weight_g", "resblocks.7.convs1.1.weight_v", "resblocks.7.convs1.2.bias", "resblocks.7.convs1.2.weight_g", "resblocks.7.convs1.2.weight_v", "resblocks.7.convs2.0.bias", "resblocks.7.convs2.0.weight_g", "resblocks.7.convs2.0.weight_v", "resblocks.7.convs2.1.bias", "resblocks.7.convs2.1.weight_g", "resblocks.7.convs2.1.weight_v", "resblocks.7.convs2.2.bias", "resblocks.7.convs2.2.weight_g", "resblocks.7.convs2.2.weight_v", "resblocks.8.convs1.0.bias", "resblocks.8.convs1.0.weight_g", "resblocks.8.convs1.0.weight_v", "resblocks.8.convs1.1.bias", "resblocks.8.convs1.1.weight_g", "resblocks.8.convs1.1.weight_v", "resblocks.8.convs1.2.bias", "resblocks.8.convs1.2.weight_g", "resblocks.8.convs1.2.weight_v", "resblocks.8.convs2.0.bias", "resblocks.8.convs2.0.weight_g", "resblocks.8.convs2.0.weight_v", "resblocks.8.convs2.1.bias", "resblocks.8.convs2.1.weight_g", "resblocks.8.convs2.1.weight_v", "resblocks.8.convs2.2.bias", "resblocks.8.convs2.2.weight_g", "resblocks.8.convs2.2.weight_v". 
	size mismatch for conv_pre.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for conv_pre.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
	size mismatch for conv_pre.weight_v: copying a param with shape torch.Size([512, 80, 7]) from checkpoint, the shape in current model is torch.Size([256, 80, 7]).
	size mismatch for ups.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for ups.0.weight_g: copying a param with shape torch.Size([512, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 1, 1]).
	size mismatch for ups.0.weight_v: copying a param with shape torch.Size([512, 256, 16]) from checkpoint, the shape in current model is torch.Size([256, 128, 16]).
	size mismatch for ups.1.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ups.1.weight_g: copying a param with shape torch.Size([256, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 1, 1]).
	size mismatch for ups.1.weight_v: copying a param with shape torch.Size([256, 128, 16]) from checkpoint, the shape in current model is torch.Size([128, 64, 16]).
	size mismatch for ups.2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([32]).
	size mismatch for ups.2.weight_g: copying a param with shape torch.Size([128, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1, 1]).
	size mismatch for ups.2.weight_v: copying a param with shape torch.Size([128, 64, 4]) from checkpoint, the shape in current model is torch.Size([64, 32, 8]).
```

Do I need to re-implement the key mapping for the model?
